version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: resume
    volumes:
      - dbresume:/var/lib/mysql
    ports:
      - 3305:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8084:80
    environment:
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=pass
    depends_on:
      - db
volumes:
  dbresume: